export const actions = {
  FEATURE_PROPERTY_LIST_REQUEST: 'FEATURE_PROPERTY_LIST_REQUEST',
  FEATURE_PROPERTY_LIST_SUCCESS: 'FEATURE_PROPERTY_LIST_SUCCESS',
  FEATURE_PROPERTY_LIST_ERROR: 'FEATURE_PROPERTY_LIST_ERROR',

  AUTH_FEATURE_PROPERTY_LIST_REQUEST: 'AUTH_FEATURE_PROPERTY_LIST_REQUEST',
  AUTH_FEATURE_PROPERTY_LIST_SUCCESS: 'AUTH_FEATURE_PROPERTY_LIST_SUCCESS',
  AUTH_FEATURE_PROPERTY_LIST_ERROR: 'AUTH_FEATURE_PROPERTY_LIST_ERROR',

  FAVORITE_PROPERTY_LIST_REQUEST: 'FAVORITE_PROPERTY_LIST_REQUEST',
  FAVORITE_PROPERTY_LIST_SUCCESS: 'FAVORITE_PROPERTY_LIST_SUCCESS',
  FAVORITE_PROPERTY_LIST_ERROR: 'FAVORITE_PROPERTY_LIST_ERROR',

  PROPERTY_SEARCH_REQUEST: 'PROPERTY_SEARCH_REQUEST',
  PROPERTY_SEARCH_SUCCESS: 'PROPERTY_SEARCH_SUCCESS',
  PROPERTY_SEARCH_ERROR: 'PROPERTY_SEARCH_ERROR',

  AUTH_PROPERTY_SEARCH_REQUEST: 'AUTH_PROPERTY_SEARCH_REQUEST',
  AUTH_PROPERTY_SEARCH_SUCCESS: 'AUTH_PROPERTY_SEARCH_SUCCESS',
  AUTH_PROPERTY_SEARCH_ERROR: 'AUTH_PROPERTY_SEARCH_ERROR',

  SINGLE_PROPERTY_REQUEST: 'SINGLE_PROPERTY_REQUEST',
  SINGLE_PROPERTY_SUCCESS: 'SINGLE_PROPERTY_SUCCESS',
  SINGLE_PROPERTY_ERROR: 'SINGLE_PROPERTY_ERROR',

  PER_USER_PROPERTY_REQUEST: 'PER_USER_PROPERTY_REQUEST',
  PER_USER_PROPERTY_SUCCESS: 'PER_USER_PROPERTY_SUCCESS',
  PER_USER_PROPERTY_ERROR: 'PER_USER_PROPERTY_ERROR',

  DELETE_USER_PROPERTY_REQUEST: 'DELETE_USER_PROPERTY_REQUEST',
  DELETE_USER_PROPERTY_SUCCESS: 'DELETE_USER_PROPERTY_SUCCESS',
  DELETE_USER_PROPERTY_ERROR: 'DELETE_USER_PROPERTY_ERROR',

  PER_MONTH_RENT_REQUEST: 'PER_MONTH_RENT_REQUEST',
  PER_MONTH_RENT_SUCCESS: 'PER_MONTH_RENT_SUCCESS',
  PER_MONTH_RENT_ERROR: 'PER_MONTH_RENT_ERROR',

  FAVORITE_PROPERTY_REQUEST: 'FAVORITE_PROPERTY_REQUEST',
  FAVORITE_PROPERTY_SUCCESS: 'FAVORITE_PROPERTY_SUCCESS',
  FAVORITE_PROPERTY_ERROR: 'FAVORITE_PROPERTY_ERROR',

  SEARCH_REQUEST_DATA: 'SEARCH_REQUEST_DATA',

  FAVORITE_PAGE_NUMBER: 'FAVORITE_PAGE_NUMBER',

  DATE_POPUP_OPEN:'DATE_POPUP_OPEN',

  getPropertyFeatureList: () => ({
    type: actions.FEATURE_PROPERTY_LIST_REQUEST,
  }),

  getAuthPropertyFeatureList: () => ({
    type: actions.AUTH_FEATURE_PROPERTY_LIST_REQUEST,
  }),

  getFavouritePropertyList: (payload: { pageNo: number }) => ({
    type: actions.FAVORITE_PROPERTY_LIST_REQUEST,
    payload: payload,
  }),

  searchProperty: (payload: any) => ({
    type: actions.PROPERTY_SEARCH_REQUEST,
    payload: payload,
  }),

  searchAuthProperty: (payload: any) => ({
    type: actions.AUTH_PROPERTY_SEARCH_REQUEST,
    payload: payload,
  }),

  getSingleProperty: (payload: any) => ({
    type: actions.SINGLE_PROPERTY_REQUEST,
    payload: payload,
  }),

  getPerUserProperty: (payload: any) => ({
    type: actions.PER_USER_PROPERTY_REQUEST,
    payload: payload,
  }),

  deleteUserProperty: (payload: any) => ({
    type: actions.DELETE_USER_PROPERTY_REQUEST,
    payload: payload,
  }),

  getPerMonthRent: (payload: { id: number }) => ({
    type: actions.PER_MONTH_RENT_REQUEST,
    payload: payload,
  }),

  addFavourite: (payload: any) => ({
    type: actions.FAVORITE_PROPERTY_REQUEST,
    payload: payload,
  }),

  searchData: (payload: any) => ({
    type: actions.SEARCH_REQUEST_DATA,
    payload: payload,
  }),

  favoritePageNumber: (payload: any) => ({
    type: actions.FAVORITE_PAGE_NUMBER,
    payload: payload,
  }),

    datePopupOpen:(payload:any)=>({
      type:actions.DATE_POPUP_OPEN,
      payload:payload
    })

};

export default actions;
