export const actions = {
  GET_DUPLICATE_LISTING_REQUEST: 'GET_DUPLICATE_LISTING_REQUEST',
  GET_DUPLICATE_LISTING_SUCCESS: 'GET_DUPLICATE_LISTING_SUCCESS',
  GET_DUPLICATE_LISTING_ERROR: 'GET_DUPLICATE_LISTING_ERROR',

  GET_MOBILE_NUMBER_REQUEST: 'GET_MOBILE_NUMBER_REQUEST',
  GET_MOBILE_NUMBER_SUCCESS: 'GET_MOBILE_NUMBER_SUCCESS',
  GET_MOBILE_NUMBER_ERROR: 'GET_MOBILE_NUMBER_ERROR',

  REQUEST_OTP_REQUEST: 'REQUEST_OTP_REQUEST',
  REQUEST_OTP_SUCCESS: 'REQUEST_OTP_SUCCESS',
  REQUEST_OTP_ERROR: 'REQUEST_OTP_ERROR',

  SUBMIT_OTP_REQUEST: 'SUBMIT_OTP_REQUEST',
  SUBMIT_OTP_SUCCESS: 'SUBMIT_OTP_SUCCESS',
  SUBMIT_OTP_ERROR: 'SUBMIT_OTP_ERROR',

  GET_STEP2_DATA_REQUEST: 'GET_STEP2_DATA_REQUEST',
  GET_STEP2_DATA_SUCCESS: 'GET_STEP2_DATA_SUCCESS',

  GET_STEP3_DATA_REQUEST: 'GET_STEP3_DATA_REQUEST',
  GET_STEP3_DATA_SUCCESS: 'GET_STEP3_DATA_SUCCESS',

  GET_STEP4_DATA_REQUEST: 'GET_STEP4_DATA_REQUEST',
  GET_STEP4_DATA_SUCCESS: 'GET_STEP4_DATA_SUCCESS',

  GET_STEP5_DATA_REQUEST: 'GET_STEP5_DATA_REQUEST',
  GET_STEP5_DATA_SUCCESS: 'GET_STEP5_DATA_SUCCESS',

  GET_STEP6_DATA_REQUEST: 'GET_STEP6_DATA_REQUEST',
  GET_STEP6_DATA_SUCCESS: 'GET_STEP6_DATA_SUCCESS',

  GET_STEP7_DATA_REQUEST: 'GET_STEP7_DATA_REQUEST',
  GET_STEP7_DATA_SUCCESS: 'GET_STEP7_DATA_SUCCESS',
  GET_STEP_DATA_ERROR: 'GET_STEP_DATA_ERROR',

  EDIT_PROPERTY_STEP2_REQUEST: 'EDIT_PROPERTY_STEP2_REQUEST',
  EDIT_PROPERTY_STEP2_SUCCESS: 'EDIT_PROPERTY_STEP2_SUCCESS',
  EDIT_PROPERTY_STEP2_ERROR: 'EDIT_PROPERTY_STEP2_ERROR',

  EDIT_PROPERTY_STEP3_REQUEST: 'EDIT_PROPERTY_STEP3_REQUEST',
  EDIT_PROPERTY_STEP3_SUCCESS: 'EDIT_PROPERTY_STEP3_SUCCESS',
  EDIT_PROPERTY_STEP3_ERROR: 'EDIT_PROPERTY_STEP3_ERROR',

  EDIT_PROPERTY_STEP4_REQUEST: 'EDIT_PROPERTY_STEP4_REQUEST',
  EDIT_PROPERTY_STEP4_SUCCESS: 'EDIT_PROPERTY_STEP4_SUCCESS',
  EDIT_PROPERTY_STEP4_ERROR: 'EDIT_PROPERTY_STEP4_ERROR',

  EDIT_PROPERTY_STEP5_REQUEST: 'EDIT_PROPERTY_STEP5_REQUEST',
  EDIT_PROPERTY_STEP5_SUCCESS: 'EDIT_PROPERTY_STEP5_SUCCESS',
  EDIT_PROPERTY_STEP5_ERROR: 'EDIT_PROPERTY_STEP5_ERROR',

  EDIT_PROPERTY_STEP6_REQUEST: 'EDIT_PROPERTY_STEP6_REQUEST',
  EDIT_PROPERTY_STEP6_SUCCESS: 'EDIT_PROPERTY_STEP6_SUCCESS',
  EDIT_PROPERTY_STEP6_ERROR: 'EDIT_PROPERTY_STEP6_ERROR',

  EDIT_PROPERTY_STEP7_REQUEST: 'EDIT_PROPERTY_STEP7_REQUEST',
  EDIT_PROPERTY_STEP7_SUCCESS: 'EDIT_PROPERTY_STEP7_SUCCESS',
  EDIT_PROPERTY_STEP7_ERROR: 'EDIT_PROPERTY_STEP7_ERROR',

  DELETE_PROPERTY_REQUEST: 'DELETE_PROPERTY_REQUEST',
  DELETE_PROPERTY_SUCCESS: 'DELETE_PROPERTY_SUCCESS',
  DELETE_PROPERTY_ERROR: 'DELETE_PROPERTY_ERROR',

  SET_PROPERTY_ID_SUCCESS: 'SET_PROPERTY_ID_SUCCESS',

  getDuplicateListing: () => ({
    type: actions.GET_DUPLICATE_LISTING_REQUEST,
  }),

  getMobileNumber: (payload) => ({
    type: actions.GET_MOBILE_NUMBER_REQUEST,
    payload: payload,
  }),

  requestOtp: (payload) => ({
    type: actions.REQUEST_OTP_REQUEST,
    payload: payload,
  }),

  submitOtp: (payload) => ({
    type: actions.SUBMIT_OTP_REQUEST,
    payload: payload,
  }),

  getStep2Data: (payload) => ({
    type: actions.GET_STEP2_DATA_REQUEST,
    payload: payload,
  }),
  getStep3Data: (payload) => ({
    type: actions.GET_STEP3_DATA_REQUEST,
    payload: payload,
  }),
  getStep4Data: (payload) => ({
    type: actions.GET_STEP4_DATA_REQUEST,
    payload: payload,
  }),
  getStep5Data: (payload) => ({
    type: actions.GET_STEP5_DATA_REQUEST,
    payload: payload,
  }),
  getStep6Data: (payload) => ({
    type: actions.GET_STEP6_DATA_REQUEST,
    payload: payload,
  }),
  getStep7Data: (payload) => ({
    type: actions.GET_STEP7_DATA_REQUEST,
    payload: payload,
  }),

  editStep2Details: (payload) => ({
    type: actions.EDIT_PROPERTY_STEP2_REQUEST,
    payload: payload,
  }),
  editStep3Details: (payload) => ({
    type: actions.EDIT_PROPERTY_STEP3_REQUEST,
    payload: payload,
  }),
  editStep4Details: (payload) => ({
    type: actions.EDIT_PROPERTY_STEP4_REQUEST,
    payload: payload,
  }),
  editStep5Details: (payload) => ({
    type: actions.EDIT_PROPERTY_STEP5_REQUEST,
    payload: payload,
  }),
  editStep6Details: (payload) => ({
    type: actions.EDIT_PROPERTY_STEP6_REQUEST,
    payload: payload,
  }),
  editStep7Details: (payload) => ({
    type: actions.EDIT_PROPERTY_STEP7_REQUEST,
    payload: payload,
  }),
  deleteProperty: (payload) => ({
    type: actions.DELETE_PROPERTY_REQUEST,
    payload: payload,
  }),
};
export default actions;
