import Document, { Html, Head, Main, NextScript } from 'next/document';
import { ServerStyleSheet } from 'styled-components';
import { I18Provider, LOCALES } from '../i18n/index';

export default class MyDocument extends Document {
  static async getInitialProps(ctx) {
    const sheet = new ServerStyleSheet();
    const originalRenderPage = ctx.renderPage;

    try {
      ctx.renderPage = () =>
        originalRenderPage({
          enhanceApp: (App) => (props) =>
            sheet.collectStyles(<App {...props} />),
        });

      const initialProps = await Document.getInitialProps(ctx);
      return {
        ...initialProps,
        styles: (
          <>
            {initialProps.styles}
            {sheet.getStyleElement()}
          </>
        ),
      };
    } finally {
      sheet.seal();
    }
  }

  render() {
    return (
      <Html lang='en'>
        <Head>
          <title>RentSmartly</title>
          <meta name='description' content='Generated by create next app' />
          <link rel='icon' type='image/x-icon' href='/favicon.ico' />
        </Head>
        <body>
          <I18Provider locale={LOCALES.ENGLISH}>
            <Main />
            <NextScript />
          </I18Provider>
        </body>
      </Html>
    );
  }
}
