import Head from 'next/head';
import React from 'react';

const HeadTitle = ({ title }: any) => {
  return (
    <>
      <Head>
        <title>{title}</title>
        <meta name='description' content='Generated by create next app' />
      </Head>
    </>
  );
};

export default HeadTitle;
