export const actions = {
  PROPERTY_LIST_REQUEST: 'PROPERTY_LIST_REQUEST',
  PROPERTY_LIST_SUCCESS: 'PROPERTY_LIST_SUCCESS',
  PROPERTY_LIST_ERROR: 'PROPERTY_LIST_ERROR',

  ADMIN_DELETE_PROPERTY_REQUEST: 'ADMIN_DELETE_PROPERTY_REQUEST',
  ADMIN_DELETE_PROPERTY_SUCCESS: 'ADMIN_DELETE_PROPERTY_SUCCESS',
  ADMIN_DELETE_PROPERTY_ERROR: 'ADMIN_DELETE_PROPERTY_ERROR',

  ADMIN_SINGLE_PROPERTY_REQUEST: 'ADMIN_SINGLE_PROPERTY_REQUEST',
  ADMIN_SINGLE_PROPERTY_SUCCESS: 'ADMIN_SINGLE_PROPERTY_SUCCESS',
  ADMIN_SINGLE_PROPERTY_ERROR: 'ADMIN_SINGLE_PROPERTY_ERROR',

  GET_TENANT_LIST_REQUEST: 'GET_TENANT_LIST_REQUEST',
  GET_TENANT_LIST_SUCCESS: 'GET_TENANT_LIST_SUCCESS',
  GET_TENANT_LIST_ERROR: 'GET_TENANT_LIST_ERROR',

  TENANT_DETAILS_REQUEST: 'TENANT_DETAILS_REQUEST',
  TENANT_DETAILS_SUCCESS: 'TENANT_DETAILS_SUCCESS',
  TENANT_DETAILS_ERROR: 'TENANT_DETAILS_ERROR',

  getPropertyList: (payload: any) => ({
    type: actions.PROPERTY_LIST_REQUEST,
    payload: payload,
  }),

  getSingleProperty: (payload: any) => ({
    type: actions.ADMIN_SINGLE_PROPERTY_REQUEST,
    payload: payload,
  }),

  deletePropertyAdmin: (payload: any) => ({
    type: actions.ADMIN_DELETE_PROPERTY_REQUEST,
    payload: payload,
  }),

  getTenantList: (payload: any) => ({
    type: actions.GET_TENANT_LIST_REQUEST,
    payload: payload,
  }),

  getTenantDetails: (payload: any) => ({
    type: actions.TENANT_DETAILS_REQUEST,
    payload: payload,
  }),
};
export default actions;
